language: java
dist: trusty  
#sudo: false
sudo: required
install: true

addons:
  sonarcloud:
    organization: "zakharskaletskyi"
    token:
      secure: "3215046d97c64441cd26c8cc645720ffcd9cf6d4"

jdk:
  - oraclejdk8
  
script:
#- sonar-scanner

- mvn install
#mvn clean package sonar:sonar
mvn sonar:sonar

#- mvn clean verify sonar:sonar 
#- mvn sonar:sonar
# other script steps might be done before running the actual analysis
#- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - '$HOME/.sonar/cache'
    - '$HOME/.m2/repository' #work without this, maybe delete

    
